# Generated by Django 2.2.5 on 2019-11-21 13:09

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=2000)),
                ('mac', models.CharField(blank=True, max_length=2000)),
                ('manager', models.CharField(blank=True, max_length=2000)),
                ('room', models.CharField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('address', models.CharField(blank=True, max_length=2000)),
                ('telephone', models.CharField(blank=True, max_length=2000)),
                ('poster_code', models.CharField(blank=True, max_length=2000)),
                ('pathology_tel', models.CharField(blank=True, max_length=2000)),
                ('consult_sel', models.CharField(blank=True, max_length=2000)),
                ('internet_url', models.CharField(blank=True, max_length=2000)),
                ('report_model', models.CharField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('age', models.IntegerField(blank=True)),
                ('birth', models.CharField(blank=True, max_length=2000)),
                ('gender', models.IntegerField(blank=True)),
                ('patient_id', models.CharField(blank=True, max_length=2000)),
                ('patient_phone', models.CharField(blank=True, max_length=2000)),
                ('menses', models.CharField(blank=True, max_length=2000)),
                ('menses_date', models.CharField(blank=True, max_length=2000)),
                ('specimen_id', models.CharField(blank=True, max_length=2000)),
                ('specimen_date', models.CharField(blank=True, max_length=2000)),
                ('specimen_type', models.CharField(blank=True, max_length=2000)),
                ('reference_hospital', models.CharField(blank=True, max_length=2000)),
                ('reference_department', models.CharField(blank=True, max_length=2000)),
                ('reference_doctor', models.CharField(blank=True, max_length=2000)),
                ('AIdiagnosis', models.IntegerField(blank=True)),
                ('AIgrade', models.CharField(blank=True, max_length=2000)),
                ('AIinformation', models.CharField(blank=True, max_length=2000)),
                ('suggestion1', models.CharField(blank=True, max_length=2000)),
                ('suggestion2', models.CharField(blank=True, max_length=2000)),
                ('verifier', models.CharField(blank=True, max_length=2000)),
                ('author', models.CharField(blank=True, max_length=2000)),
                ('approver', models.CharField(blank=True, max_length=2000)),
                ('technician', models.CharField(blank=True, max_length=2000)),
                ('multi_focus', models.IntegerField(blank=True)),
                ('scan_date', models.CharField(blank=True, max_length=2000)),
                ('bbox_array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, size=None)),
                ('t_bbox_array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, size=None)),
                ('m_bbox_array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, size=None)),
                ('report_bbox_array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, size=None)),
                ('diagnosisValue', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('status', models.CharField(blank=True, default='create', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('submit', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
