# Generated by Django 2.2.5 on 2019-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='AIdiagnosis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='multi_focus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
