# Generated by Django 2.2.5 on 2019-11-26 09:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191126_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scan',
            name='diagnosisValue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='m_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scan',
            name='report_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scan',
            name='t_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
