# Generated by Django 2.2.5 on 2019-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191126_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
