# Generated by Django 2.2.5 on 2019-12-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191218_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
