# Generated by Django 2.2.5 on 2019-12-19 03:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_scan_scan_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='smear_bbox',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
