# Generated by Django 2.2.5 on 2020-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_init_admin_hospital_20200205'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscope',
            name='equip_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='microscope',
            name='offsetX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microscope',
            name='offsetY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
