# Generated by Django 2.2.5 on 2020-02-13 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0013_auto_20200207_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='occupied_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occupied_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
