# Generated by Django 2.2.5 on 2020-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_scan_occupied_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='smear_bbox',
            new_name='scout_log',
        ),
    ]
