# Generated by Django 2.2.5 on 2020-03-25 03:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200318_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='p_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
