# Generated by Django 2.2.5 on 2020-03-25 07:07

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_scan_p_bbox_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='agc_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scan',
            name='h_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scan',
            name='l_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
