# Generated by Django 2.2.5 on 2020-03-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200325_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='AIscore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
