# Generated by Django 2.2.5 on 2020-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_scan_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(blank=True, default='scan', max_length=200, null=True),
        ),
    ]
