# Generated by Django 2.2.5 on 2020-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200331_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='menses',
            field=models.CharField(blank=True, max_length=2000, null=True),
        )
    ]
