# Generated by Django 2.2.5 on 2020-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_department_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='micro_flag',
            field=models.BooleanField(default=False),
        ),
    ]
