# Generated by Django 2.2.5 on 2020-04-09 01:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_scan_micro_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='i_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
