# Generated by Django 2.2.5 on 2020-04-10 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_scan_i_bbox_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
