# Generated by Django 2.2.5 on 2020-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='upload_flag',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
