# Generated by Django 2.2.5 on 2020-05-20 04:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_scan_reserved_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='lep_bbox_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
