# Generated by Django 2.2.5 on 2020-06-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_scan_lep_bbox_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='diagnosis_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
