# Generated by Django 2.2.5 on 2020-10-19 09:51

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0036_auto_20200917_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('hostname', models.CharField(default='NS', max_length=500, null=True)),
                ('ip', models.CharField(blank=True, max_length=2000, null=True)),
                ('mac', models.CharField(blank=True, max_length=2000, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sp_machine',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SPMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straw_tip_tray', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('infiltration_tray', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('slide_supply', models.BooleanField(default=False)),
                ('slide_charger_grip', models.BooleanField(default=False)),
                ('slide_cartridge', models.BooleanField(default=False)),
                ('trip_supply', models.BooleanField(default=False)),
                ('he_supply', models.FloatField(blank=True, null=True)),
                ('ea_supply', models.FloatField(blank=True, null=True)),
                ('ethanol_supply', models.BooleanField(default=False)),
                ('water_supply', models.BooleanField(default=False)),
                ('detergent_supply', models.BooleanField(default=False)),
                ('acrylate_supply', models.FloatField(blank=True, null=True)),
                ('resin_supply', models.FloatField(blank=True, null=True)),
                ('finished_drawer', models.BooleanField(default=False)),
                ('waste_tank', models.BooleanField(default=False)),
                ('vacuum_tank', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sp_monitor',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='physician',
            name='operator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SPSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_scan', models.CharField(blank=True, max_length=2000, null=True)),
                ('barcode_img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), null=True, size=None)),
                ('barcode_print', models.CharField(blank=True, max_length=2000, null=True)),
                ('hostname', models.CharField(default='NS', max_length=500, null=True)),
                ('cycle_status', models.CharField(blank=True, max_length=500, null=True)),
                ('finish_status', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('finish_time', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sp_machine', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.SPMachine')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_sample',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='spmachine',
            name='monitor',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.SPMonitor'),
        ),
        migrations.CreateModel(
            name='SPAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=2000, null=True)),
                ('brief', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('related_sample', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sp_machine', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.SPMachine')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_alert',
                'ordering': ['created'],
            },
        ),
    ]
