# Generated by Django 2.2.5 on 2020-10-22 02:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20201019_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spmonitor',
            old_name='trip_supply',
            new_name='tris_supply',
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='settling_wheel',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
