# Generated by Django 2.2.5 on 2020-10-26 07:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20201022_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='sample_slot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None),
        ),
    ]
