# Generated by Django 2.2.5 on 2020-11-19 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_scan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='owner',
            field=models.ForeignKey(db_column='username', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
