# Generated by Django 2.2.5 on 2020-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_scan_measurement_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='cleaning_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='component_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='machine_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='waste_bucket',
            field=models.BooleanField(default=False),
        ),
    ]
