# Generated by Django 2.2.5 on 2021-01-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_modify_admin_20201217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=2000)),
                ('user', models.CharField(max_length=2000)),
                ('action', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'common_action',
                'ordering': ['created'],
            },
        ),
    ]
