# Generated by Django 2.2.5 on 2021-03-30 06:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_add_scheduled_tasks_20210306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spmonitor',
            old_name='straw_tip_tray',
            new_name='tip_tray',
        ),
        migrations.RemoveField(
            model_name='spmonitor',
            name='infiltration_tray',
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='filtration_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=django.contrib.postgres.fields.jsonb.JSONField()),
        ),
    ]
