# Generated by Django 2.2.5 on 2021-04-02 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20210330_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spmonitor',
            name='filtration_status',
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='filtration',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
