# Generated by Django 2.2.5 on 2021-04-12 13:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20210402_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='tip_deposit',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='spmonitor',
            name='tip_tray',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None),
        ),
    ]
