# Generated by Django 2.2.5 on 2021-04-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_auto_20210412_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spmonitor',
            name='tip_deposit',
        ),
    ]
