# Generated by Django 2.2.5 on 2021-04-12 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_remove_spmonitor_tip_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='tip_deposit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
