# Generated by Django 2.2.5 on 2021-04-30 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_spmonitor_tip_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spsample',
            old_name='cycle_status',
            new_name='process_status',
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_clip',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_filtration',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_liquid',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_slide',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_tip',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='reserve_wheel',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
