# Generated by Django 2.2.5 on 2021-05-07 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_auto_20210430_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsample',
            name='timestamps',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
