# Generated by Django 2.2.5 on 2021-05-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_spsample_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsample',
            name='post_staining_ethanol_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='pre_staining_ethanol_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='settling_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='staining_EA_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='staining_HE_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='staining_buffer_time',
            field=models.FloatField(null=True),
        ),
    ]
