# Generated by Django 2.2.5 on 2021-05-17 03:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_auto_20210508_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='liquid',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
