# Generated by Django 2.2.5 on 2021-05-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_spmonitor_slide_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsample',
            name='name_print',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
