# Generated by Django 2.2.5 on 2021-05-24 07:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_spsample_name_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='spsample',
            name='staining_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
