# Generated by Django 2.2.5 on 2021-08-05 06:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_splog_sp_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmonitor',
            name='scheduler',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
