# Generated by Django 2.2.5 on 2021-08-10 01:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_spmonitor_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('specimen_date', models.CharField(blank=True, max_length=2000, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_date', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_hospital', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_department', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_doctor', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_specimen', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth', models.CharField(blank=True, max_length=2000, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('patient_roomNum', models.CharField(blank=True, max_length=2000, null=True)),
                ('patient_roomBed', models.CharField(blank=True, max_length=2000, null=True)),
                ('patient_roomId', models.CharField(blank=True, max_length=2000, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=2000, null=True)),
                ('menses', models.CharField(blank=True, max_length=2000, null=True)),
                ('menses_date', models.CharField(blank=True, max_length=2000, null=True)),
                ('examine_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('physical_examination_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('examine_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('outpatient_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('inpatient_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('inpatient_area', models.CharField(blank=True, max_length=2000, null=True)),
                ('inpatient_bed', models.CharField(blank=True, max_length=2000, null=True)),
                ('invoice', models.CharField(blank=True, max_length=2000, null=True)),
                ('marriage_status', models.BooleanField(null=True)),
                ('specimen_receiver', models.CharField(blank=True, max_length=2000, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(blank=True, max_length=2000, null=True)),
                ('surgery_observation', models.CharField(blank=True, max_length=2000, null=True)),
                ('clinical_history', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='specimen_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Specimen'),
        ),
    ]
