# Generated by Django 2.2.5 on 2021-08-12 06:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_auto_20210810_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefined',
            fields=[
                ('name', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('included', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
