# Generated by Django 2.2.5 on 2021-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_userdefined'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='satisfaction_nucleus_count',
            field=models.IntegerField(null=True),
        ),
    ]
