# Generated by Django 2.2.5 on 2021-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_report_satisfaction_nucleus_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sp_barcode_hospital_name',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
