# Generated by Django 2.2.5 on 2021-11-09 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_init_report_20211026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='hour_of_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='minute_of_hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='run_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
