# Generated by Django 2.2.5 on 2021-11-11 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20211109_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='micro_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
