# Generated by Django 2.2.5 on 2021-11-24 02:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_scan_micro_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='micro_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
