# Generated by Django 2.2.7 on 2022-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_auto_20211124_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_zoom_level',
            field=models.IntegerField(null=True),
        ),
    ]
