# Generated by Django 2.2.7 on 2022-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_auto_20220303_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='spalert',
            name='last_launch_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spalert',
            name='today_launch_count_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spalert',
            name='today_processing_batch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='last_factory_reset_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='last_launch_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='last_offduty_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='today_launch_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spmonitor',
            name='today_processing_batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='last_launch_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='today_launch_count_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spsample',
            name='today_processing_batch_id',
            field=models.IntegerField(null=True),
        ),
    ]
