# Generated by Django 2.2.7 on 2022-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_auto_20220310_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hospital_logo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
