# Generated by Django 2.2.7 on 2022-05-26 12:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_report_hospital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
