# Generated by Django 2.2.7 on 2022-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_report_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_process',
            field=models.CharField(default='one_level', max_length=200),
        ),
    ]
