# Generated by Django 2.2.7 on 2022-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_specimen_patient_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='backup_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='backup_folder',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='to_be_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
