# Generated by Django 2.2.7 on 2022-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_auto_20220706_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='backup_tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
