# Generated by Django 2.2.7 on 2022-10-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_scan_backup_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='approving_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='authoring_date',
            field=models.DateTimeField(null=True),
        ),
    ]
